<!-- Generated by documentation.js. Update this documentation by updating the source code. -->

### Table of Contents

-   [listen][1]
-   [GET][2]
    -   [Parameters][3]
-   [DELETE][4]
    -   [Parameters][5]
-   [PUT][6]
    -   [Parameters][7]
-   [MKCOL][8]
    -   [Parameters][9]

## listen

This fuction creates a server which listens at port 8000.

## GET

This method returns the content file or directory if it exists.

### Parameters

-   `request`  

Returns **any** shows content.

## DELETE

This method delets a directory if it exists.

### Parameters

-   `request`  

Returns **rmdir** removed path directory.

## PUT

This method adds a directory or file what path indicates.

### Parameters

-   `request`  

Returns **[request][10]** can add content to fille with pipe() or simply creates file.

## MKCOL

This method delets a directory if it exists.

### Parameters

-   `request`  

Returns **mkdir** added path directory.

[1]: #listen

[2]: #get

[3]: #parameters

[4]: #delete

[5]: #parameters-1

[6]: #put

[7]: #parameters-2

[8]: #mkcol

[9]: #parameters-3

[10]: https://developer.mozilla.org/Add-ons/SDK/High-Level_APIs/request
